build:
	GOOS=darwin GORACH=arm64 go build -o go-clipboard-monitor-darwin-arm64
	GOOS=darwin GORACH=amd64 go build -o go-clipboard-monitor-darwin-x64
	GOOS=linux GORACH=386 go build -o go-clipboard-monitor-linux-386
	GOOS=linux GORACH=arm go build -o go-clipboard-monitor-linux-arm
	GOOS=linux GORACH=arm64 go build -o go-clipboard-monitor-linux-arm64
	GOOS=linux GORACH=amd64 go build -o go-clipboard-monitor-linux-x64
	GOOS=windows GORACH=amd64 go build -o go-clipboard-monitor-linux-amd64