/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ClipboardWatcherJs {
  stop(): void
  get isRunning(): boolean
}

export declare function availableFormats(): Array<string>

export declare function clear(): Promise<void>

export declare function getBuffer(format: string): Promise<Array<number>>

export declare function getFiles(): Promise<Array<string>>

export declare function getHtml(): Promise<string>

export declare function getImageBase64(): Promise<string>

export declare function getImageBinary(): Promise<Array<number>>

export declare function getRtf(): Promise<string>

export declare function getText(): Promise<string>

export declare function hasFiles(): boolean

export declare function hasHtml(): boolean

export declare function hasImage(): boolean

export declare function hasRtf(): boolean

export declare function hasText(): boolean

export declare function setBuffer(format: string, buffer: Array<number>): Promise<void>

export declare function setFiles(files: Array<string>): Promise<void>

export declare function setHtml(html: string): Promise<void>

export declare function setImageBase64(base64Str: string): Promise<void>

export declare function setImageBinary(imageBytes: Array<number>): Promise<void>

export declare function setRtf(rtf: string): Promise<void>

export declare function setText(text: string): Promise<void>

/**
 * Start watching the clipboard for changes.
 * The callback is invoked whenever the clipboard content changes.
 * Returns a `ClipboardWatcherJs` handle that can stop the watcher.
 */
export declare function startWatch(callback: () => void): ClipboardWatcherJs
